"""refactor FeedbackStorage column names

Revision ID: 297a29427d44
Revises: 88e4b5fb0b64
Create Date: 2025-05-13 22:59:26.668806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297a29427d44'
down_revision: Union[str, None] = '88e4b5fb0b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbackstorage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('shift', sa.Text(), nullable=True),
    sa.Column('floor', sa.Text(), nullable=True),
    sa.Column('game', sa.Text(), nullable=True),
    sa.Column('gp_name_surname', sa.Text(), nullable=True),
    sa.Column('sm_name_surname', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('proof', sa.Text(), nullable=True),
    sa.Column('explanation_of_the_reason', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('forwarded_feedback', sa.Text(), nullable=True),
    sa.Column('comment_after_forwarding', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('FeedbackStorage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FeedbackStorage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Shift', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Floor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Game', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('GP_Name_Surname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('SM_Name_Surname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Proof', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Explanation_of_the_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Action_taken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Forwarded_Feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Comment_after_forwarding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='FeedbackStorage_pkey')
    )
    op.drop_table('feedbackstorage')
    # ### end Alembic commands ###
