"""init all tables

Revision ID: 394d820eabee
Revises: 
Create Date: 2025-05-12 21:06:33.893993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394d820eabee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FeedbackStorage', sa.Column('date', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('shift', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('floor', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('game', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('proof', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('explanation_of_the_reason', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('action_taken', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('forwarded_Feedback', sa.Text(), nullable=True))
    op.add_column('FeedbackStorage', sa.Column('comment_after_forwarding', sa.Text(), nullable=True))
    op.drop_column('FeedbackStorage', 'Action_taken')
    op.drop_column('FeedbackStorage', 'Shift')
    op.drop_column('FeedbackStorage', 'Comment_after_forwarding')
    op.drop_column('FeedbackStorage', 'Floor')
    op.drop_column('FeedbackStorage', 'Forwarded_Feedback')
    op.drop_column('FeedbackStorage', 'Reason')
    op.drop_column('FeedbackStorage', 'Explanation_of_the_reason')
    op.drop_column('FeedbackStorage', 'Game')
    op.drop_column('FeedbackStorage', 'Proof')
    op.drop_column('FeedbackStorage', 'Total')
    op.drop_column('FeedbackStorage', 'Date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FeedbackStorage', sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Proof', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Game', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Explanation_of_the_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Forwarded_Feedback', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Floor', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Comment_after_forwarding', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Shift', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('FeedbackStorage', sa.Column('Action_taken', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('FeedbackStorage', 'comment_after_forwarding')
    op.drop_column('FeedbackStorage', 'forwarded_Feedback')
    op.drop_column('FeedbackStorage', 'action_taken')
    op.drop_column('FeedbackStorage', 'explanation_of_the_reason')
    op.drop_column('FeedbackStorage', 'proof')
    op.drop_column('FeedbackStorage', 'total')
    op.drop_column('FeedbackStorage', 'reason')
    op.drop_column('FeedbackStorage', 'game')
    op.drop_column('FeedbackStorage', 'floor')
    op.drop_column('FeedbackStorage', 'shift')
    op.drop_column('FeedbackStorage', 'date')
    # ### end Alembic commands ###
