"""restore FeedbackStorage

Revision ID: 88e4b5fb0b64
Revises: 394d820eabee
Create Date: 2025-05-12 21:35:51.867200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e4b5fb0b64'
down_revision: Union[str, None] = '394d820eabee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FeedbackStorage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Text(), nullable=True),
    sa.Column('Shift', sa.Text(), nullable=True),
    sa.Column('Floor', sa.Text(), nullable=True),
    sa.Column('Game', sa.Text(), nullable=True),
    sa.Column('GP_Name_Surname', sa.Text(), nullable=True),
    sa.Column('SM_Name_Surname', sa.Text(), nullable=True),
    sa.Column('Reason', sa.Text(), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.Column('Proof', sa.Text(), nullable=True),
    sa.Column('Explanation_of_the_reason', sa.Text(), nullable=True),
    sa.Column('Action_taken', sa.Text(), nullable=True),
    sa.Column('Forwarded_Feedback', sa.Text(), nullable=True),
    sa.Column('Comment_after_forwarding', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FeedbackStorage')
    # ### end Alembic commands ###
