from datetime import datetime

def return_raw_tasks():
    """
    Returns a list of dictionaries representing raw tasks.
    Each dictionary contains information about a specific task.
    """
    # Example data for demonstration purposes
    # In a real scenario, this data would be fetched from a database or an API
    raw_tasks = [
            {
                "id": 1,
                "name_of_process": "SHUFFLE GENERIC",
                "source_table_type": "shuffle_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_shuffle_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 23),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_shuffle_rotation",
                "values_json": "json_data",
                "target_table_type": "generic_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_generic_shuffle",
                "last_update": datetime(2025, 4, 13, 15, 3, 59),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 2,
                "name_of_process": "SHUFFLE LEGENDZ",
                "source_table_type": "shuffle_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_shuffle_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 24),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_shuffle_rotation",
                "values_json": "json_data",
                "target_table_type": "legendz_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_legendz_shuffle",
                "last_update": datetime(2025, 4, 13, 15, 4, 1),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 3,
                "name_of_process": "SHUFFLE GSBJ",
                "source_table_type": "shuffle_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_shuffle_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 24),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_shuffle_rotation",
                "values_json": "json_data",
                "target_table_type": "gsbj_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_gsbj_shuffle",
                "last_update": datetime(2025, 4, 13, 15, 4, 4),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 4,
                "name_of_process": "SHUFFLE Main",
                "source_table_type": "shuffle_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_shuffle_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 25),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 4, 6),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 5,
                "name_of_process": "VIP Main",
                "source_table_type": "vip_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_vip_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 26),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 5, 32),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 6,
                "name_of_process": "TURKISH Main",
                "source_table_type": "vip_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_vip_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 27),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_turkish_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 4, 24),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 7,
                "name_of_process": "GENERIC Main",
                "source_table_type": "generic_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_generic_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 28),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 5, 35),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 8,
                "name_of_process": "GSBJ Main",
                "source_table_type": "gsbj_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_gsbj_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 29),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 5, 36),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 9,
                "name_of_process": "LEGENDZ Main",
                "source_table_type": "legendz_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_legendz_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 30),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 5, 38),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 10,
                "name_of_process": "TRI-STAR Main",
                "source_table_type": "tristar_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_tristar_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 30),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 5, 39),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 11,
                "name_of_process": "TritonRL Main",
                "source_table_type": "tritonrl_rotation",
                "source_page_name": "DAY 1",
                "source_page_area": "D:AC",
                "scan_group": "get_tritonrl_rotation",
                "last_scan": datetime(2025, 4, 13, 15, 14, 31),
                "scan_interval": 60,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_rotation",
                "values_json": "json_data",
                "target_table_type": "main_screen_rotation",
                "target_page_name": "DAY 1",
                "target_page_area": "D:AC",
                "update_group": "update_main",
                "last_update": datetime(2025, 4, 13, 15, 5, 41),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 12,
                "name_of_process": "Floor list VIP",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 35),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_vip_list",
                "values_json": "json_data",
                "target_table_type": "vip_rotation",
                "target_page_name": "Info",
                "target_page_area": "A3:A310",
                "update_group": "update_vip",
                "last_update": datetime(2025, 4, 7, 15, 20, 33),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 13,
                "name_of_process": "Floor list GENERIC",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 36),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_generic_list",
                "values_json": "json_data",
                "target_table_type": "generic_rotation",
                "target_page_name": "Info",
                "target_page_area": "A3:A310",
                "update_group": "update_generic",
                "last_update": datetime(2025, 4, 13, 15, 13, 37),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 14,
                "name_of_process": "Floor list LEGENDZ",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 37),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_legendz_list",
                "values_json": "json_data",
                "target_table_type": "legendz_rotation",
                "target_page_name": "Info",
                "target_page_area": "A3:A310",
                "update_group": "update_legendz",
                "last_update": datetime(2025, 4, 7, 11, 39, 44),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 15,
                "name_of_process": "Floor list TURKISH",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 37),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_turkish_list",
                "values_json": "json_data",
                "target_table_type": "vip_rotation",
                "target_page_name": "Info",
                "target_page_area": "C3:C310",
                "update_group": "update_vip",
                "last_update": datetime(2025, 4, 13, 15, 13, 40),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 16,
                "name_of_process": "Floor list GSBJ",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 37),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_gsbj_list",
                "values_json": "json_data",
                "target_table_type": "gsbj_rotation",
                "target_page_name": "Info",
                "target_page_area": "A3:A310",
                "update_group": "update_gsbj",
                "last_update": datetime(2025, 4, 13, 15, 13, 42),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 17,
                "name_of_process": "Floor list TRITONRL",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 37),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_tritonrl_list",
                "values_json": "json_data",
                "target_table_type": "tritonrl_rotation",
                "target_page_name": "Info",
                "target_page_area": "A3:A310",
                "update_group": "update_tritonrl",
                "last_update": datetime(2025, 4, 13, 15, 13, 42),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 18,
                "name_of_process": "QA list SHUFFLE",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 38),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_list",
                "values_json": "json_data",
                "target_table_type": "shuffle_rotation",
                "target_page_name": "Info",
                "target_page_area": "F3:F310",
                "update_group": "shuffle_rotation",
                "last_update": datetime(2025, 4, 13, 15, 13, 44),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
                {
                "id": 19,
                "name_of_process": "QA list VIP",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 38),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_list",
                "values_json": "json_data",
                "target_table_type": "vip_rotation",
                "target_page_name": "Info",
                "target_page_area": "F3:F310",
                "update_group": "update_vip",
                "last_update": datetime(2025, 4, 13, 15, 13, 44),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 20,
                "name_of_process": "QA list GENERIC",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 38),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_list",
                "values_json": "json_data",
                "target_table_type": "generic_rotation",
                "target_page_name": "Info",
                "target_page_area": "F3:F310",
                "update_group": "update_generic",
                "last_update": datetime(2025, 4, 13, 15, 13, 45),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 21,
                "name_of_process": "QA list LEGENDZ",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 39),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_list",
                "values_json": "json_data",
                "target_table_type": "legendz_rotation",
                "target_page_name": "Info",
                "target_page_area": "F3:F310",
                "update_group": "update_legendz",
                "last_update": datetime(2025, 4, 13, 15, 13, 47),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 22,
                "name_of_process": "QA list GSBJ",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 12),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_list",
                "values_json": "json_data",
                "target_table_type": "gsbj_rotation",
                "target_page_name": "Info",
                "target_page_area": "F3:F310",
                "update_group": "update_gsbj",
                "last_update": datetime(2025, 4, 13, 15, 13, 49),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 23,
                "name_of_process": "QA list TRITONRL",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 15, 14, 12),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_qa_list",
                "values_json": "json_data",
                "target_table_type": "tritonrl_rotation",
                "target_page_name": "Info",
                "target_page_area": "F3:F310",
                "update_group": "update_tritonrl",
                "last_update": datetime(2025, 4, 13, 15, 13, 49),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 24,
                "name_of_process": "Permits VIP",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 17, 9, 46),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_permits",
                "values_json": "json_data",
                "target_table_type": "vip_rotation",
                "target_page_name": "Permits",
                "target_page_area": "A1:K310",
                "update_group": "update_vip",
                "last_update": datetime(2025, 4, 13, 14, 39, 38),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 25,
                "name_of_process": "Permits GENERIC",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 17, 7, 32),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_permits",
                "values_json": "json_data",
                "target_table_type": "generic_rotation",
                "target_page_name": "Permits",
                "target_page_area": "A1:K310",
                "update_group": "update_generic",
                "last_update": datetime(2025, 4, 13, 14, 39, 40),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 26,
                "name_of_process": "Permits LEGENDZ",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 17, 7, 33),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_permits",
                "values_json": "json_data",
                "target_table_type": "legendz_rotation",
                "target_page_name": "Permits",
                "target_page_area": "A1:K310",
                "update_group": "update_legendz",
                "last_update": datetime(2025, 4, 13, 14, 39, 42),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            },
            {
                "id": 27,
                "name_of_process": "Permits GSBJ",
                "source_table_type": "qa_list",
                "source_page_name": "QA List",
                "source_page_area": "G:Y",
                "scan_group": "get_qa_list",
                "last_scan": datetime(2025, 4, 13, 17, 7, 34),
                "scan_interval": 1800,
                "scan_quantity": 0,
                "scan_failures": 0,
                "hash": "hash",
                "process_data_method": "process_permits",
                "values_json": "json_data",
                "target_table_type": "gsbj_rotation",
                "target_page_name": "Permits",
                "target_page_area": "A1:K310",
                "update_group": "update_gsbj",
                "last_update": datetime(2025, 4, 13, 14, 39, 45),
                "update_quantity": 0,
                "update_failures": 0,
                "start_row": 0,
                "end_row": 0,
                "need_update": 0
            }
]
    return raw_tasks

def return_tracked_tables():
    tracked_tables = [
            {"table_type": "qa_list", "spreadsheet_id": "10n0pf5qP26ALbpe0-vVlaILzmdUF8d529yN6Mt8hS9c", "valid_from": "01.01.2024", "valid_to": "31.12.2026"},
            {"table_type": "feedbacks", "spreadsheet_id": "1DrXJDAFdEm86MmKOPbiJjac6IvYmmUfjK_CFJwLr9ZM", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "bonus", "spreadsheet_id": "14q-CItoITjj2L-VdyTkhPy2umyPz9oeUzNJzHyMJLho", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "live88_bs_game", "spreadsheet_id": "16VGJ-rBYJtpli72fvJFYd0KLngaVs-0iA8KzTXWl0Vs", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "legendz_bs_game", "spreadsheet_id": "13UohkGTvMEbAUQaF5OypryuDfDKIXBZjBFohrpoHcI0", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "shuffle_rotation", "spreadsheet_id": "1GpEDNX2zpJRHjwF96Dv49H38aieEhiDS-qwSp6i-dds", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "vip_rotation", "spreadsheet_id": "1vBxIFHLkcuQ_T1LyRQx1F2UthYlk5QBJvvfqZCCCtL8", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "generic_rotation", "spreadsheet_id": "1nLTpz3Eyj86mZQYr3y3WqtAkBJ-W3mbzAOhYLuL6OLE", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "gsbj_rotation", "spreadsheet_id": "1lQ_Na96wsxPKH-lrxgC-D6BAD3z9qB8xcmL79uCxKlk", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "legendz_rotation", "spreadsheet_id": "1jsPORmAJhaLHzpJVY2W9pYqZHSHmCw84OZoY6WHlQi8", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "tristar_rotation", "spreadsheet_id": "1F2YagosDAMwlloZIe1lNwBvl1udM5YaeGtcWwpuEk94", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "tritonrl_rotation", "spreadsheet_id": "13sn64-v1sL5eU8oVqOGEBu9dIkWjf32i3O9z23y5m9c", "valid_from": "01.04.2025", "valid_to": "30.04.2025"},
            {"table_type": "main_screen_rotation", "spreadsheet_id": "1mNjJR9qGyF__7JjcVIL5BuC3_-HGH4KQkTLtXtVjbh4", "valid_from": "01.04.2025", "valid_to": "30.04.2025"}
        ]
    return tracked_tables